### ISSUE TITLE
Add config for ignore-volume-az

### ISSUE THREAD

**Issue by johnsca** [juju-solutions/charm-openstack-integrator#11]
The default should be true, but it should be possible to override it.

This fixes issues with using Cinder + Ceph as the storage provider where there is only one AZ used for Cinder but multiple for Nova.

**Comment by johnsca** [comment]
https://kubernetes.io/docs/concepts/cluster-administration/cloud-providers/#block-storage

**Comment by tvansteenburgh** [comment]
Issue moved to https://bugs.launchpad.net/bugs/1809349.
